version: "3"

services:
  app:
    profiles: ["devcontainer"]
    container_name: rexbole-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - database
    stdin_open: true
    tty: true
    env_file: .env.development
    environment:
      DEVCONTAINER: 1
    network_mode: host

  database:
    container_name: rexbole-database
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rexbole
    volumes:
      - rexbole-database:/var/lib/postgresql/data

  cache:
    container_name: rexbole-cache
    image: redis:7-alpine
    ports:
      - 6380:6379

  caddy:
    profiles: ["deploy"]
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    network_mode: host

volumes:
  rexbole-database:
